### ISSUE TITLE
Include some test features

### ISSUE THREAD

**Issue by ender-null** [yukuku/telebot#1]
It would be cool if you add some examples sending images, stickers, forwarding messages or videos.
Or if you have enough time, some kind of modules or plugins to extend the functionality of the bot.

**Comment by yukuku** [comment]
I haven't had time to do and test it, but if you manage to do one, please make a pull request or just send me the code and I will integrate it to the template code.

**Comment by telegrambeans** [comment]
can you include to send picture from web as message ?

**Comment by yukuku** [comment]
Sample of sending image is done. You can now send `/image` and the bot will reply with a generated image.
