### ISSUE TITLE
Don't speak in groups

### ISSUE THREAD

**Issue by Malnacid0** [yukuku/telebot#13]
Hello again,

my bot works perfectly in private chat, but not in groups.

Why?

Thank You.

**Comment by yukuku** [comment]
Have you done the set privacy thing?

**Comment by Malnacid0** [comment]
Yes, the problem is the bot is down, I'm sorry.

**Comment by ADTC** [comment]
Wondering this too. If you have two bots and you @mention one bot, both bots will reply! If you don't @mention any bot, no bot will reply. Strange!

I think there are some rules regarding how bots behave in groups. I need to find them and go through them again.

Edit: Ah the privacy setting... :P

**Comment by Malnacid0** [comment]
Solved, there are my problem. I'm sorry!
