### ISSUE TITLE
Send a picture of a link ?

### ISSUE THREAD

**Issue by idreamsi** [yukuku/telebot#15]
Hi
How can I send a picture of a link? 
for example : https://www.google.co.uk/images/srpr/logo11w.png

**Comment by bostrot** [comment]
I don't really know what you mean but if you mean this: [Screenshot](http://puu.sh/jnRjV/5e36ceae1b.jpg)
You have to create a new reply and change 
`'disable_web_page_preview': 'true'`
to 
`'disable_web_page_preview': 'false'` 
example: [Screenshot](http://puu.sh/jnRrc/27653d0527.png)

**Comment by ghost** [comment]
@Bostrot I think he means that bot uploads picture (as picture) from link with picture.

EDIT: If this, then I would like to see this how to do it too.

**Comment by idreamsi** [comment]
Thanks ;)
Problem is solved.

**Comment by tahara2130** [comment]
how you solved the trouble?
