### ISSUE TITLE
Write to all who opened the chat with my bot

### ISSUE THREAD

**Issue by bostrot** [yukuku/telebot#17]
Hi,
I want my bot to write after a command to all chat_id 's. How can I do this?

ex:
If I write: `/writetoallusers test`
All groups and people who started the chat with my bot (with `/start`) shall get the text: `test`

**Comment by srazi** [comment]
Hi
You have to store all chat_ids (that enabled your bot) and then within a loop send message to them one by one. your `reply` function should accept chat_id as an argument. Don't send message to those that use `/stop` because then your bot will be a bad bot ;)

**Comment by bostrot** [comment]
Thanks for you answer. Can you write me a sample? I am not so good in python :-)
