### ISSUE TITLE
send image, videos.

### ISSUE THREAD

**Issue by Prog-Mustafa** [yukuku/telebot#20]
Hi, I have my bot working by now, but the thing is it can only send text. I have seen in the Bot API there are functions to send phots, videos... but I can't get it to work. Someone has achieved it?
plzz need help

**Comment by idreamsi** [comment]
Hi
I have the same problem, How can I send a file (Document) ?

**Comment by deepenmhrj** [comment]
I got it to work with a particular image on server, but I am looking to be able to use google API to display image search results!

**Comment by Prog-Mustafa** [comment]
use this code
reply(img=urllib2.urlopen('https://www.image.jpg').read())
