### ISSUE TITLE
Sending a welcome message to new group members

### ISSUE THREAD

**Issue by Igetin** [yukuku/telebot#25]
Hi, how do I check if a new user is added to a group, using Telegram Bot starter kit? I'm planning to send a message every time someone joins a group chat.

Thanks in advance!

**Comment by yukuku** [comment]
It is not possible AFAIK. Telegram bots do not receive such events.

**Comment by Igetin** [comment]
I actually solved this already, there is a `new_chat_participant` parameter in the API, which can be used to message newly joined users in a group.

**Comment by ADTC** [comment]
@Igetin Put it on your fork? :)

**Comment by sziyan** [comment]
Would appreciate it if someone could give a example of the code.

Cant seem to get it to work.

**Comment by Abdujabboraka** [comment]
how to check users added members count in telegram group using telebot python
