### ISSUE TITLE
Markdown Parse Mode

### ISSUE THREAD

**Issue by coriumalpha** [yukuku/telebot#27]
Telegram Bot API now [supports Markdown](https://core.telegram.org/bots/api#using-markdown) on [sendMessage method](https://core.telegram.org/bots/api#sendmessage).

It can be used by adding `'parse_mode': 'Markdown'` to `reply {if msg}` definition or by creating a new reply class (`replyMarkdown` for example) with the Markdown parse mode included.
Choosing the second option implies calling `replyMarkdown(str(markdown_formated_message))` instead of `reply(str(non_markdown_formated_message))`.

**Comment by yukuku** [comment]
This is an enhancement. The aim of this project is to show how to receive and send a simple message containing text or image.

**Comment by kazzkiq** [comment]
It's been 3 years since Telegram added support do Markdown. Do you still have the same opinion on it not serving the purpose of this project?

It would be really cool to be able to use markdown on it!
