### ISSUE TITLE
"A request to the Telegram API was unsuccessful"

### ISSUE THREAD

**Issue by onionpsy** [yukuku/telebot#29]
Hello,

Sometimes I got this error message : 

```
2015-10-11 17:48:12,169 (__init__.py:159) ERROR - TeleBot: "A request to the Telegram API was unsuccessful. The server returned HTTP 502 Bad Gateway. Response body:
[<html>
<head><title>502 Bad Gateway</title></head>
<body bgcolor="white">
<center><h1>502 Bad Gateway</h1></center>
<hr><center>nginx/1.9.1</center>
</body>
</html>
]"
```

I'm using the update_listener like that : 

``` Python

tg_bot.set_update_listener(self.on_messages)
tg_bot.polling()

def on_message():
    for message in messages:
        # ...
        tg_bot.send_message(message.chat.id, '')
```

I've seen that this kind of error is due to telegram server itself but is it possible ton make a way that we can handle these exceptions ? 

Thanks :)

**Comment by ADTC** [comment]
Will [error handling](https://docs.python.org/2/tutorial/errors.html#handling-exceptions) help?

**Comment by onionpsy** [comment]
No, that's the problem. I don't get any exception, juste this error in the stdout. It would be perfect if could handle this as an exception.

**Comment by ADTC** [comment]
That's funny, I don't find `set_update_listener` in the code. Can you fork the project and push your new code?
