### ISSUE TITLE
reply_markup

### ISSUE THREAD

**Issue by fopina** [yukuku/telebot#3]
Hey, I'm trying to build a full class to wrap up the new bot API (at https://github.com/fopina/py-tgbot) and just stumbled in your example but it seems you haven't tried to use any custom keyboards with sendMessage reply_markup.
I can use the custom keyboard as long as I don't specify any extra options, otherwise it seems the whole object is ignored..
Have you used it (outside this github repo)?

**Comment by yukuku** [comment]
No, I haven't tried the custom keyboard option..

**Comment by telegrambeans** [comment]
can you iclude greeting new group member ?
