### ISSUE TITLE
I'm banned 

### ISSUE THREAD

**Issue by xFraz** [yukuku/telebot#34]
You are not a human, you are banned. If you are a human, contact us. http://blog.simsimi.com

Help mee!

**Comment by ilbonte** [comment]
I have the same issue... what is going on? 
EDIT:
Found the problem: in the example the bot makes a request to that website: https://github.com/yukuku/telebot/blob/master/main.py#L135

**Comment by yukuku** [comment]
Now the bot does not make use of simsimi.com to generate replies.
