### ISSUE TITLE
Improvements

### ISSUE THREAD

**Issue by Walkman100** [yukuku/telebot#40]
After forking this project I have made a few improvements that I think should be in by default, e.g. markdown/HTML responses and better logging. I haven't opened a PR because I don't know if they would be accepted, being a "starter" kit, or if anyone who can merge changes is still active.

**Comment by yukuku** [comment]
I will update the sample not to use simsimi since it is not working anymore. As for other features I don't want to include it, the reason being it a starter kit.

**Comment by Walkman100** [comment]
can I still make a PR for better logging? all it does is put the messages on one line so as not to clutter up the log viewer: https://github.com/Walkman100/telebot/commit/4f6697b9d975948ce612f964ae25abd50c3a5f76
