### ISSUE TITLE
Where is GoogleAppEngineLauncher?

### ISSUE THREAD

**Issue by eckucukoglu** [yukuku/telebot#60]
From the step 21;

Where is GoogleAppEngineLauncher? I have installed sdk for both for Windows and Ubuntu, however none of them include GoogleAppEngineLauncher.

**Comment by MasterMB2** [comment]
i guess you should download it manually from google

**Comment by eckucukoglu** [comment]
Yes, but I couldn't find any application like that for linux. I think, not only name of the binary should be written, but also more descriptive information about the Google App Engine Launcher? or what refers it should be given in Readme.
