### ISSUE TITLE
How to download the repository in .zip now?

### ISSUE THREAD

**Issue by ghost** [yukuku/telebot#61]
I guess the layout of https://console.cloud.google.com/project has changed since this tutorial was written and now I can't find a way to download the repository (step 17 of the tutorial).

**Comment by yukuku** [comment]
Fixed in 7579a97. That instruction is for the GitHub page, not the cloud console page.

**Comment by ghost** [comment]
Okay, sorry for my misunderstanding. So cloning the *telebot* repository, right?
